### ISSUE TITLE
:V

### ISSUE THREAD

**Issue by MrSamydenub** [bsnk-dev/pnwkit.gs#1]
I hate this product.
It works too well.
Code is ment to be buggy and trash. 
Why does this work.
Illigal.
U go to jail for being too good at your job.

**Comment by bsnk-dev** [comment]
> I hate this product.
> 
> It works too well.
> 
> Code is ment to be buggy and trash. 
> 
> Why does this work.
> 
> Illigal.
> 
> U go to jail for being too good at your job. 

Thanks! I really believe that getting API data onto a spreadsheet should be an easy as building one.

Have a great day!
Bann
